[[audits.jxl]]
who = "Luca Versari <veluca@google.com>"
criteria = ["safe-to-deploy"]
version = "0.1.1"
notes = "Based on ub-risk-1 by joshlf@google.com and the lack of filesystem usage outside tests."

[[audits.jxl]]
who = "Łukasz Anforowicz <lukasza@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.1.3"
notes = "Based on a review by @anforowicz (https://github.com/libjxl/jxl-rs/pull/518) and the lack of filesystem usage outside tests."

[[audits.jxl_simd]]
who = "Łukasz Anforowicz <lukasza@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.1.3"
notes = "Based on a review by @anforowicz (https://github.com/libjxl/jxl-rs/pull/518) and the lack of filesystem usage outside tests."

[[audits.jxl]]
who = "Łukasz Anforowicz <lukasza@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.1.5"
notes = "Delta review from v0.1.3: no safety-relevant changes (except for a simple fix under stacked borrows)."

[[audits.jxl_simd]]
who = "Łukasz Anforowicz <lukasza@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.1.5"
notes = "Delta review from v0.1.3: no safety-relevant changes."

[[audits.jxl]]
who = "Łukasz Anforowicz <lukasza@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.3.0"
notes = "Delta review from v0.1.5"

[[audits.jxl_simd]]
who = "Łukasz Anforowicz <lukasza@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.3.0"
notes = "Delta review from v0.1.5"

[[audits.jxl_macros]]
who = "Luca Versari <veluca@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.3.0"
notes = "No unsafe code, no fs access outside of test-only functionality"

[[audits.jxl_transforms]]
who = "Luca Versari <veluca@chromium.org>"
criteria = ["safe-to-deploy"]
version = "0.3.0"
notes = "No unsafe code, no fs access"
